name: Ethash
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/ethash

defaults:
  run:
    working-directory: packages/ethash

jobs:
  test-ethash:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Use npm v7 for workspaces support 
        run: npm i -g npm@7

      - run: npm i
        working-directory: ${{github.workspace}}

      - run: npm run coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: ethash
        if: ${{ matrix.node-version == 12 }}

      - run: npm run lint
